version: '3.0'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes: 
      - static_volume:/usr/src/app/client/build/
    ports:
      - 5000
    restart: unless-stopped
  
  nginx:
    build: ./nginx
    volumes: 
      - static_volume:/usr/src/app/client/build/
    ports:
      - 1337:1337
    depends_on:
      - app
    restart: unless-stopped

volumes:
  static_volume:
